/* Generated By:JJTree: Do not edit this line. ASTLambda.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLambda extends SimpleNode {
  public ASTLambda(int id) {
    super(id);
  }

  public ASTLambda(LispParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LispParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=92bf57f07ccb7de22824840a9ce4c7c8 (do not edit this line) */
