/* Generated By:JavaCC: Do not edit this line. LispParserTreeConstants.java Version 5.0 */
public interface LispParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTARITHEXPR = 1;
  public int JJTIDENTIFIER = 2;
  public int JJTNUM = 3;


  public String[] jjtNodeName = {
    "Program",
    "ArithExpr",
    "Identifier",
    "Num",
  };
}
/* JavaCC - OriginalChecksum=b2b48ef480833e3375c1951605b21c0a (do not edit this line) */
