/* Generated By:JavaCC: Do not edit this line. LispParserTreeConstants.java Version 5.0 */
public interface LispParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTFUNCTIONEXPR = 1;
  public int JJTNAMEDFUNCTIONAPP = 2;
  public int JJTLAMBDAEXPR = 3;
  public int JJTARITHEXPR = 4;
  public int JJTIDENTIFIER = 5;
  public int JJTNUM = 6;


  public String[] jjtNodeName = {
    "Program",
    "FunctionExpr",
    "NamedFunctionApp",
    "LambdaExpr",
    "ArithExpr",
    "Identifier",
    "Num",
  };
}
/* JavaCC - OriginalChecksum=244916f976d1f8aa45cb343f0e9d005b (do not edit this line) */
