/* Generated By:JavaCC: Do not edit this line. LispParserVisitor.java Version 5.0 */
public interface LispParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTFunctionExpr node, Object data);
  public Object visit(ASTLambdaExpr node, Object data);
  public Object visit(ASTArithExpr node, Object data);
  public Object visit(ASTIdentifier node, Object data);
  public Object visit(ASTNum node, Object data);
}
/* JavaCC - OriginalChecksum=0db6cc36484e99d6ad4293e39a046da3 (do not edit this line) */
