/* Generated By:JavaCC: Do not edit this line. LispParserVisitor.java Version 5.0 */
public interface LispParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTNum node, Object data);
  public Object visit(ASTExpr node, Object data);
}
/* JavaCC - OriginalChecksum=1a763d1543640d1005a5030b156addf0 (do not edit this line) */
