/* Generated By:JJTree&JavaCC: Do not edit this line. LispParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LispParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LAMBDA = 7;
  /** RegularExpression Id. */
  int LET = 8;
  /** RegularExpression Id. */
  int LPAR = 9;
  /** RegularExpression Id. */
  int RPAR = 10;
  /** RegularExpression Id. */
  int SEMI = 11;
  /** RegularExpression Id. */
  int OP = 12;
  /** RegularExpression Id. */
  int INTEGER = 13;
  /** RegularExpression Id. */
  int IDENTIFIER = 14;
  /** RegularExpression Id. */
  int ERROR = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"LAMBDA\"",
    "\"LET\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "<OP>",
    "<INTEGER>",
    "<IDENTIFIER>",
    "<ERROR>",
  };

}
