/* Generated By:JavaCC: Do not edit this line. LispParserTreeConstants.java Version 5.0 */
public interface LispParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTNUM = 1;
  public int JJTEXPR = 2;


  public String[] jjtNodeName = {
    "Program",
    "Num",
    "Expr",
  };
}
/* JavaCC - OriginalChecksum=0ac50a12c526207379e366bab4aae72e (do not edit this line) */
