/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package crono;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NIL = 6;
  /** RegularExpression Id. */
  int LPAR = 7;
  /** RegularExpression Id. */
  int RPAR = 8;
  /** RegularExpression Id. */
  int STRING = 9;
  /** RegularExpression Id. */
  int DOUBLE = 10;
  /** RegularExpression Id. */
  int INTEGER = 11;
  /** RegularExpression Id. */
  int COMBSYMBOL = 12;
  /** RegularExpression Id. */
  int SYMBOL = 13;
  /** RegularExpression Id. */
  int ERROR = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<NIL>",
    "\"(\"",
    "\")\"",
    "<STRING>",
    "<DOUBLE>",
    "<INTEGER>",
    "<COMBSYMBOL>",
    "<SYMBOL>",
    "<ERROR>",
  };

}
