/* Generated By: ecp456     CSID&JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LAMBDA = 6;
  /** RegularExpression Id. */
  int LET = 7;
  /** RegularExpression Id. */
  int LPAR = 8;
  /** RegularExpression Id. */
  int RPAR = 9;
  /** RegularExpression Id. */
  int NUMBER = 10;
  /** RegularExpression Id. */
  int OP = 11;
  /** RegularExpression Id. */
  int SYMBOL = 12;
  /** RegularExpression Id. */
  int ERROR = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\"lambda\"",
    "\"let\"",
    "\"(\"",
    "\")\"",
    "<NUMBER>",
    "<OP>",
    "<SYMBOL>",
    "<ERROR>",
  };

}
